import { useEffect, useState } from 'react'
type QQStatus = { has_secret?: boolean; app_id?: string | null; openid_bound?: boolean; binding_state?: string; gateway_status?: string; connection_error?: string | null; secure_store_status?: 'READY' | 'UNAVAILABLE_CURRENT_LOGON_SESSION'; secure_store_reason?: string; deployment_managed?: boolean }
export function QQBotSettings() {
  const [status, setStatus] = useState<QQStatus>({}); const [appId, setAppId] = useState(''); const [secret, setSecret] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  const load = async (): Promise<QQStatus> => { const response = await fetch('/api/trade-coach/qqbot/settings', { cache: 'no-store' }); if (!response.ok) throw new Error('读取配置状态失败'); const value = await response.json() as QQStatus; setStatus(value); return value }
  useEffect(() => { void load().catch((error) => setMessage(error instanceof Error ? error.message : '读取失败')) }, [])
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setMessage(''); try { const response = await fetch('/api/trade-coach/qqbot/settings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ app_id: appId, app_secret: secret }) }); const value = await response.json(); if (!response.ok) throw new Error(value.message || '保存失败'); setSecret(''); setStatus(value); setMessage('已保存。请向机器人发送“绑定”完成首次绑定。') } catch (error) { setMessage(error instanceof Error ? error.message : '保存失败') } finally { setBusy(false) } }
  const clearBinding = async () => { if (!window.confirm('确认清除 QQ 绑定？不会删除 AppSecret。')) return; setBusy(true); try { const response = await fetch('/api/trade-coach/qqbot/binding', { method: 'DELETE' }); const value = await response.json(); if (!response.ok) throw new Error(value.message || '清除失败'); setStatus(value); setMessage('绑定已清除。') } catch (error) { setMessage(error instanceof Error ? error.message : '清除失败') } finally { setBusy(false) } }
  const unavailable = status.secure_store_status === 'UNAVAILABLE_CURRENT_LOGON_SESSION' || status.deployment_managed === true;
  return <section className="panel qqbot-panel"><div className="panel__header"><span className="panel__eyebrow">LOCAL NOTIFICATION / QQBOT</span><h3>官方 QQ 机器人</h3></div><div className="qqbot-warning">请勿在页面输入或查看旧 AppSecret；密钥仅保存于 Windows Credential Manager。</div>{unavailable && <div className="qqbot-warning">请在Windows正常登录后由自动任务启动工作台</div>}<div className="qqbot-status">绑定状态：{status.binding_state || 'WAITING_BINDING'} · Gateway：{status.gateway_status || 'DISABLED'}{status.connection_error ? ` · ${status.connection_error}` : ''}</div><form className="qqbot-form" onSubmit={save}><label>AppID<input value={appId} onChange={(event) => setAppId(event.target.value)} autoComplete="off" placeholder="填写官方 QQ Bot AppID" disabled={unavailable} /></label><label>AppSecret（新密钥）<input type="password" value={secret} onChange={(event) => setSecret(event.target.value)} autoComplete="new-password" placeholder={status.has_secret ? '留空保持当前密钥' : '首次配置必填'} disabled={unavailable} /></label><button className="primary-button" disabled={busy || unavailable || (!secret && !status.has_secret)}>{busy ? '保存中…' : '保存配置'}</button></form>{status.openid_bound && <button onClick={clearBinding} disabled={busy}>清除绑定</button>}{message && <div className="form-message" role="status">{message}</div>}<small className="settings-hint">配置后向机器人发送严格指令“绑定”。仅首次私聊可绑定；群聊、重复或无关消息不会绑定。清除绑定不会删除 AppSecret。</small></section>
}
